language: ruby
rvm:
  - 2.5.1
cache: bundler
before_script:
  - cp config/database.travis.yml config/database.yml
  - RAILS_ENV=test bin/rails db:create
  - RAILS_ENV=test bin/rails db:schema:load
addons:
  postgresql: "9.6"
script:
  - bundle exec rspec
