version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    command: "./bin/rails s -p 8000 -b '0.0.0.0'"
    depends_on:
      - database
    stdin_open: true
    tty: true
  database:
    image: postgres:10
    volumes:
      - pgdata://var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: kool_cloud_api_development

volumes:
  pgdata:
